apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-deploy
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deploy
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: Always 
        env:
        - name: MYSQL_ROOT_PASSWORD
            # value: Ts1488
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_password
        - name: MYSQL_PASSWORD
            # value: juliet
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_admin_password
        - name: MYSQL_USER
            # value: mehmet
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_USER
        - name: MYSQL_DATABASE
            # value: phonebook
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_DATABASE     
        volumeMounts:
        - name: mysql-persistent-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
